binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  QuasiQuotes: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: QuasiText 0.1.2.5

  Hackage: prettyclass 1.0.0.0

  Hackage: language-glsl 0.1.1

  Hackage: union-find 0.2

  Hackage: aeson-pretty 0.7.1

  Git: https://github.com/elm-lang/elm-compiler.git 629a71d8e88da1e3ba8fa1827729837623dff51e

  Git: https://github.com/JoeyEremondi/core.git d9404abd4ad04cccd02fcaec91c61d8a9414b79b

  Git: https://github.com/JoeyEremondi/elm-build-lib.git c0a47cdb337625ea70d6b065de14a40ec573751f

  Git: https://github.com/JoeyEremondi/haskelm.git fef9d90bd4e1d3473ec48d2fa3152b8a3692bcc7'
ghc-args: []
excluded-modules: []
